version: "3.3"

services:

  pgsql:
    image: postgres:13
    container_name: ${COMPOSE_PROJECT_NAME}_backend_db
    restart: unless-stopped
    networks:
      - country_migrations_network
    volumes:
      - country_migrations_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  country_migrations_network:

volumes:
  country_migrations_data:
